--
-- Author: lipeng
-- Date: 2015-07-24 11:42:55
-- 文件路径配置

FILE_PATH = {}
FILE_PATH.PATH_VIEWS = "app.views"
FILE_PATH.PATH_VIEWS_BASE = FILE_PATH.PATH_VIEWS..".base"
FILE_PATH.PATH_VIEWS_UI_TEMPLEATE = FILE_PATH.PATH_VIEWS..".ui_templeate"
FILE_PATH.PATH_VIEWS_BATTLEFIELD = FILE_PATH.PATH_VIEWS..".battlefield"
FILE_PATH.PATH_VIEWS_GAMEWORLD = FILE_PATH.PATH_VIEWS..".gameWorld"
FILE_PATH.PATH_PUBLIC = FILE_PATH.PATH_VIEWS.."app.public"

